version: "3"

services: 
  engine:
    platform: linux/amd64
    image: my_template:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    volumes:
      - ./results:/home/results
    command: bash
